import type { OnMount } from '@monaco-editor/react';

type Monaco = Parameters<OnMount>[1];
const C = {
  fg: 'BCBEC4',
  comment: '7A7E85',
  docComment: '5F826B',
  keyword: 'CF8E6D',
  string: '6AAB73',
  number: '2AACB8',
  regexp: '42C3D4',
  function: '56A8F5',
  method: '57AAF7',
  property: 'C77DBB',
  annotation: 'B3AE60',
  tag: 'D5B778',
  customTag: '2FBAA3',
  typeParam: '16BAAC',
  invalid: 'F75464',
} as const;
const monoBracket = `#${C.fg}`;
function cssVar(name: string, fallback: string): string {
  if (typeof window === 'undefined') {
    return fallback;
  }
  const value = getComputedStyle(document.documentElement).getPropertyValue(name).trim();
  return value || fallback;
}
export function defineAppThemes(monaco: Monaco) {
  monaco.editor.defineTheme('harnesys-dark', {
    base: 'vs-dark',
    inherit: false,
    rules: [
      { token: '', foreground: C.fg },
      { token: 'invalid', foreground: C.invalid },
      { token: 'emphasis', fontStyle: 'italic' },
      { token: 'strong', fontStyle: 'bold' },
      { token: 'comment', foreground: C.comment },
      { token: 'comment.doc', foreground: C.docComment, fontStyle: 'italic' },
      { token: 'comment.md', foreground: C.comment },
      { token: 'keyword', foreground: C.keyword },
      { token: 'keyword.flow', foreground: C.keyword },
      { token: 'keyword.json', foreground: C.keyword },
      { token: 'keyword.other', foreground: C.keyword },
      { token: 'string', foreground: C.string },
      { token: 'string.escape', foreground: C.keyword },
      { token: 'string.key.json', foreground: C.property },
      { token: 'string.value.json', foreground: C.string },
      { token: 'string.sql', foreground: C.string },
      { token: 'string.yaml', foreground: C.string },
      { token: 'string.html', foreground: C.string },
      { token: 'number', foreground: C.number },
      { token: 'number.hex', foreground: C.number },
      { token: 'regexp', foreground: C.regexp },
      { token: 'type', foreground: C.fg },
      { token: 'type.identifier', foreground: C.fg },
      { token: 'class', foreground: C.fg },
      { token: 'class.name', foreground: C.fg },
      { token: 'interface', foreground: C.fg },
      { token: 'enum', foreground: C.fg },
      { token: 'struct', foreground: C.fg },
      { token: 'typeParameter', foreground: C.typeParam },
      { token: 'function', foreground: C.function },
      { token: 'function.name', foreground: C.function },
      { token: 'member', foreground: C.method },
      { token: 'method', foreground: C.method },
      { token: 'key', foreground: C.property },
      { token: 'variable', foreground: C.fg },
      { token: 'variable.name', foreground: C.fg },
      { token: 'variable.predefined', foreground: C.keyword },
      { token: 'variable.parameter', foreground: C.fg },
      { token: 'constant', foreground: C.property },
      { token: 'annotation', foreground: C.annotation },
      { token: 'tag', foreground: C.tag },
      { token: 'tag.id', foreground: C.tag },
      { token: 'tag.class', foreground: C.tag },
      { token: 'meta.tag', foreground: C.tag },
      { token: 'meta.scss', foreground: C.tag },
      { token: 'metatag', foreground: C.tag },
      { token: 'metatag.content.html', foreground: C.tag },
      { token: 'metatag.html', foreground: C.tag },
      { token: 'metatag.xml', foreground: C.tag },
      { token: 'attribute.name', foreground: C.fg },
      { token: 'attribute.value', foreground: C.fg },
      { token: 'attribute.value.number', foreground: C.number },
      { token: 'attribute.value.number.css', foreground: C.number },
      { token: 'attribute.value.unit', foreground: C.number },
      { token: 'attribute.value.unit.css', foreground: C.number },
      { token: 'attribute.value.hex', foreground: C.number },
      { token: 'attribute.value.hex.css', foreground: C.number },
      { token: 'attribute.value.html', foreground: C.string },
      { token: 'attribute.value.xml', foreground: C.string },
      { token: 'delimiter', foreground: C.fg },
      { token: 'delimiter.bracket', foreground: C.fg },
      { token: 'delimiter.parenthesis', foreground: C.fg },
      { token: 'delimiter.angle', foreground: C.tag },
      { token: 'delimiter.html', foreground: C.tag },
      { token: 'delimiter.xml', foreground: C.tag },
      { token: 'delimiter.cdata', foreground: C.tag },
      { token: 'operator', foreground: C.fg },
      { token: 'identifier', foreground: C.fg },
    ],
    colors: {
      'editor.background': cssVar('--background', '#0f1114'),
      'editor.foreground': `#${C.fg}`,
      'editorLineNumber.foreground': '#4B5059',
      'editorLineNumber.activeForeground': '#A1A3AB',
      'editor.lineHighlightBackground': '#1F202466',
      'editor.selectionBackground': '#264F78',
      'editor.inactiveSelectionBackground': '#264F7880',
      'editorCursor.foreground': '#CED0D6',
      'editorWidget.background': '#2B2D30',
      'editorWidget.border': '#43454A',
      'editorWidget.foreground': `#${C.fg}`,
      'editorGutter.background': cssVar('--background', '#0f1114'),
      'editorBracketMatch.background': '#43454A',
      'editorBracketHighlight.foreground1': monoBracket,
      'editorBracketHighlight.foreground2': monoBracket,
      'editorBracketHighlight.foreground3': monoBracket,
      'editorBracketHighlight.foreground4': monoBracket,
      'editorBracketHighlight.foreground5': monoBracket,
      'editorBracketHighlight.foreground6': monoBracket,
      'editorBracketHighlight.unexpectedBracket.foreground': monoBracket,
      'editorIndentGuide.background1': '#26282D',
      'editorIndentGuide.activeBackground1': '#3B3E45',
      'editorWhitespace.foreground': '#E3E4E229',
      'editorError.foreground': `#${C.invalid}`,
      'editorWarning.foreground': '#F2C55C',
      'editorInfo.foreground': '#75BEFF',
      'editorSuggestWidget.background': '#2B2D30',
      'editorSuggestWidget.border': '#43454A',
      'editorSuggestWidget.foreground': `#${C.fg}`,
      'editorSuggestWidget.selectedBackground': '#2E436E',
      'editorHoverWidget.background': '#2B2D30',
      'editorHoverWidget.border': '#43454A',
      'editor.findMatchBackground': '#214283',
      'editor.findMatchHighlightBackground': '#EA5C0055',
      'scrollbarSlider.background': '#8a909859',
      'scrollbarSlider.hoverBackground': '#8a90988c',
      'scrollbarSlider.activeBackground': '#8a9098b3',
    },
  });
  monaco.editor.defineTheme('harnesys-light', {
    base: 'vs',
    inherit: true,
    rules: [],
    colors: {
      'editor.background': cssVar('--background', '#f4f5f6'),
      'editor.foreground': cssVar('--foreground', '#16181d'),
      'editorLineNumber.foreground': '#c5c9ce',
      'editorLineNumber.activeForeground': '#9aa1a8',
      'editor.lineHighlightBackground': '#eceeef80',
      'editor.selectionBackground': '#c4622d33',
      'editorCursor.foreground': cssVar('--live', '#c4622d'),
      'editorWidget.background': cssVar('--card', '#fbfbfc'),
      'editorWidget.border': cssVar('--border', '#e2e4e7'),
      'editorGutter.background': cssVar('--background', '#f4f5f6'),
      'scrollbarSlider.background': '#66707859',
      'scrollbarSlider.hoverBackground': '#6670788c',
      'scrollbarSlider.activeBackground': '#667078b3',
    },
  });
}
