import type { AgentDefinition } from '../domain/agent-definition.ts';
import type { HookBinding } from '../domain/hook.ts';
import type { PackRegistration } from '../domain/pack.ts';
import type { ArtifactStore } from '../ports/artifacts.ts';
import type { AgentsResolve } from '../ports/create-runtime.ts';
import type { Logger } from '../ports/logger.ts';
import type { ModelsPort, ProviderConfig } from '../ports/models.ts';
import type { PathsConfig } from '../ports/paths.ts';
import type { PermissionMap } from '../ports/permissions.ts';
import type { RunEventStore } from '../ports/run-event-store.ts';
import type { RunLifecycleStore } from '../ports/run-lifecycle-store.ts';
import type { RuntimeState } from '../ports/runtime-state.ts';
import type { SkillRegistry } from '../ports/skills.ts';
import type { ToolDefinition } from '../ports/tools.ts';
import type { CapabilitySet, CapabilityUniverse } from './capability-set.ts';
import type { HookEmitCtx } from './hooks/emit-hook.ts';
import type { LlmNoteProvider } from './llm-notes.ts';
import type { RunEventFeed } from './run-event-feed.ts';
export type RunEngineDeps = {
  lifecycle: RunLifecycleStore;
  events: RunEventStore;
  feed: RunEventFeed;
  instanceId: string;
  leaseTtlMs?: number;
  renewMs?: number;
  models: ProviderConfig[] | ModelsPort;
  toolRegistry: Map<string, ToolDefinition>;
  toolMessages: 'barrier' | 'ordered';
  mergeState?: (key: string, a: unknown, b: unknown) => unknown;
  artifacts?: ArtifactStore;
  packRegistrations?: PackRegistration[];
  skills?: SkillRegistry;
  agents: AgentsResolve;
  hooks?: HookBinding[];
  logger?: Logger;
};
export type RunTargetOpts = {
  state: RuntimeState;
  agent: AgentDefinition;
  permissions?: PermissionMap;
  paths?: PathsConfig;
  notes?: LlmNoteProvider[];
  packs?: PackRegistration[];
  capabilitySet?: CapabilitySet;
  universe?: CapabilityUniverse;
  skills?: SkillRegistry;
  hooks?: HookBinding[];
  hooksEmit?: HookEmitCtx;
  binDirs?: string[];
};
export type RunEngine = {
  execute(runId: string, opts: RunTargetOpts): Promise<void>;
  stop(): void;
  close(): void;
};
