#!/usr/bin/env bun
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
const root = join(import.meta.dirname, "..");
const docsDir = join(root, "docs");
const outPath = join(root, "HARNESYS.md");
const TOPIC_RE = /^(\d{2})-.+\.md$/;
function topicFiles(names: string[]): string[] {
    return names
        .filter((n) => TOPIC_RE.test(n))
        .sort((a, b) => Number(a.slice(0, 2)) - Number(b.slice(0, 2)));
}
function rewriteDocLinks(body: string): string {
    return body.replace(/\]\(\.\/(\d{2}-[a-z0-9-]+)\.md(#[^)]+)?\)/gi, (_m, file: string, hash: string | undefined) => {
        if (hash)
            return `](${hash})`;
        return `](#${file})`;
    });
}
function sectionAnchor(filename: string, body: string): string {
    const base = filename.replace(/\.md$/, "");
    return `<a id="${base}"></a>\n\n${body.trim()}\n`;
}
async function main() {
    const names = await readdir(docsDir);
    const ordered = ["README.md", ...topicFiles(names)];
    const missing = ordered.filter((n) => !names.includes(n));
    if (missing.length) {
        throw new Error(`docs merge: missing files: ${missing.join(", ")}`);
    }
    const parts: string[] = [];
    for (const name of ordered) {
        const raw = await readFile(join(docsDir, name), "utf8");
        const body = rewriteDocLinks(raw);
        if (name === "README.md") {
            parts.push(body.trim());
        }
        else {
            parts.push(sectionAnchor(name, body).trimEnd());
        }
    }
    const banner = "<!-- Generated by `bun run docs:merge`. Edit files under docs/, not this file. -->\n\n";
    const merged = banner + parts.join("\n\n---\n\n") + "\n";
    await writeFile(outPath, merged, "utf8");
    console.log(`Wrote ${outPath} (${ordered.length} files)`);
}
await main();
